### ISSUE TITLE
Is there a chance to modify it and make it work for english texts instead of Chinese?

### ISSUE THREAD

**Issue by Ali-Nass** [Jasonnor/tf-idf-python#2]
I want to get a tf-idf python script that would get me keywords (by weight) from a text. Exactly what you're doing but for English text instead of Chinese.

**Comment by Jasonnor** [comment]
Hi, this will be simpler, because we can use blanks to separate words in English.
You can refer to other repo such as: https://github.com/hrs/python-tf-idf

**Comment by Ali-Nass** [comment]
Hi, Thank you for replying, but I want to extract keywords from a document (using tf Idf) rather than compare 2 documents (unless im missunderstanding something!)

Edit: I miss understood something (kinda big) about tf-idf, excuse me for the dumb request! Thanks for the help tho.
